### ISSUE TITLE
I have problem to transform the EAD xsd to xml

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/EAD3#545]
## Creator of issue

1. Gilda Ferrandino
2. gferrandino@unior.it
3.
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [x] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [x] Other

## Reporting a bug

* Text: I am using Oxygen to transform the xsd to xml, but not all elements are 
included in the final xml.
Is there an xml version? In the portal ( [https://www.loc.gov/ead/](https://www.loc.gov/ead/) )I couldn't 
find it.

**Comment by alexduryee** [comment]
I'm not entirely clear as to what the issue is - what process is being run on the XSD, and what is the expected output?  Is this via oXygen's Generate Sample XML Files tool?

**Comment by kerstarno** [comment]
> I'm not entirely clear as to what the issue is - what process is being run on the XSD, and what is the expected output? Is this via oXygen's Generate Sample XML Files tool?

@alexduryee - I'm currently reaching out to the colleague who submitted this issue via the TS-EAS webform to find out more. Will update the issue accordingly once I've heard back from her.

**Comment by kerstarno** [comment]
Gathered feedback from within the EAD team and other members of TS-EAS, but the overall conclusion has been that the easiest way to get to a reusable template that has a `<c>` that contains all desired child elements would be to create an EAD document that looks however wanted, save it, and then use that as the base document for all new EADs.  Instead of inserting a new <c> element, one could then copy/paste the example one in the template.  

For a more automatised approach, one would probably have to create a custom version of the EAD schema that defines all  desired elements as ‘required’ children of <c> as well as an XML editor that supports the automatic insertion of required subelements. The drawback of this scenario, however, is that by defining those child element as required, you lose any flexibility for the odd case where you might not want all of them.

Feedback provided to the original reporter via email.
